/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JPanel;
import GUI.CreacionUsuarios;
import GUI.User;
import javax.swing.JOptionPane;
/**
 *
 * @author BAC
 */
public class Escritorio extends javax.swing.JFrame {
    
    public String nombreIngresado;
    public String tipoIngresado;
    public String contra;

    CreacionUsuarios CU = new CreacionUsuarios();
    ManejoFiles MD = new ManejoFiles();
    ImagenFondo ejemplo = new ImagenFondo();
    
    public Escritorio() {
        this.setContentPane(ejemplo);
        initComponents();
    }
 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnArchivos = new javax.swing.JButton();
        btnAgregarUsuarios = new javax.swing.JButton();
        btnMusica = new javax.swing.JButton();
        btnFotos = new javax.swing.JButton();
        btnNotas = new javax.swing.JButton();
        btnCMD = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnArchivos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/finder_macos_bigsur_icon_190173.png"))); // NOI18N
        btnArchivos.setBorder(null);
        btnArchivos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnArchivosMouseClicked(evt);
            }
        });
        btnArchivos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnArchivosActionPerformed(evt);
            }
        });
        getContentPane().add(btnArchivos, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 670, 50, 50));

        btnAgregarUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/settings_setting_options_icon_181546.png"))); // NOI18N
        btnAgregarUsuarios.setBorder(null);
        btnAgregarUsuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAgregarUsuariosMouseClicked(evt);
            }
        });
        btnAgregarUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarUsuariosActionPerformed(evt);
            }
        });
        getContentPane().add(btnAgregarUsuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 670, 50, 50));

        btnMusica.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Music_31107.png"))); // NOI18N
        btnMusica.setBorder(null);
        btnMusica.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMusicaMouseClicked(evt);
            }
        });
        btnMusica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMusicaActionPerformed(evt);
            }
        });
        getContentPane().add(btnMusica, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 670, 50, 50));

        btnFotos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Photos_31086.png"))); // NOI18N
        btnFotos.setBorder(null);
        btnFotos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnFotosMouseClicked(evt);
            }
        });
        getContentPane().add(btnFotos, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 670, 50, 50));

        btnNotas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Notes_31095.png"))); // NOI18N
        btnNotas.setBorder(null);
        btnNotas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNotasActionPerformed(evt);
            }
        });
        getContentPane().add(btnNotas, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 670, 50, 50));

        btnCMD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/terminal_macos_bigsur_icon_189655.png"))); // NOI18N
        btnCMD.setBorder(null);
        btnCMD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCMDActionPerformed(evt);
            }
        });
        getContentPane().add(btnCMD, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 670, 50, 50));

        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Slir.png"))); // NOI18N
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 656, 70, 70));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/dock.png"))); // NOI18N
        jLabel1.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                jLabel1ComponentResized(evt);
            }
        });
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 660, 1250, 70));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCMDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCMDActionPerformed
        // TODO add your handling code here:
        CMD cmd = new CMD();
        cmd.show();
    }//GEN-LAST:event_btnCMDActionPerformed

    private void btnAgregarUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarUsuariosActionPerformed
        // TODO add your handling code here:
         if("Administrador".equals(tipoIngresado)){
            CU.show();
        }else{
            JOptionPane.showMessageDialog(this, "Esta opcion no esta disponible para usted");
        }
    }//GEN-LAST:event_btnAgregarUsuariosActionPerformed

    private void jLabel1ComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jLabel1ComponentResized
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel1ComponentResized

    private void btnArchivosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnArchivosMouseClicked
        // TODO add your handling code here:
        ManejoFiles MF = new ManejoFiles();
        MF.show();
        
    }//GEN-LAST:event_btnArchivosMouseClicked

    private void btnMusicaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMusicaMouseClicked
        // TODO add your handling code here:
        PlayerMemo play = new PlayerMemo();
        play.show();
    }//GEN-LAST:event_btnMusicaMouseClicked

    private void btnFotosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFotosMouseClicked
        // TODO add your handling code here:
        VisordeImagenes VI = new VisordeImagenes();
        VI.nombre= this.nombreIngresado;
        VI.show();
    }//GEN-LAST:event_btnFotosMouseClicked

    private void btnAgregarUsuariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAgregarUsuariosMouseClicked
        // TODO add your handling code here:
        if("Administrador".equals(tipoIngresado)){
            CU.show();
        }else{
            JOptionPane.showMessageDialog(this, "Esta opcion no esta disponible para usted");
        }
    }//GEN-LAST:event_btnAgregarUsuariosMouseClicked

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnArchivosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnArchivosActionPerformed
        // TODO add your handling code here:
        ManejoFiles MF = new ManejoFiles();
        MF.show();
    }//GEN-LAST:event_btnArchivosActionPerformed

    private void btnMusicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMusicaActionPerformed
        // TODO add your handling code here:
        PlayerMemo play = new PlayerMemo();
        
        play.show();
    }//GEN-LAST:event_btnMusicaActionPerformed

    private void btnNotasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNotasActionPerformed
        // TODO add your handling code here:
        blocNotas bloc = new blocNotas();
        bloc.show();
    }//GEN-LAST:event_btnNotasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Escritorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Escritorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Escritorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Escritorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InicioSesion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarUsuarios;
    private javax.swing.JButton btnArchivos;
    private javax.swing.JButton btnCMD;
    private javax.swing.JButton btnFotos;
    private javax.swing.JButton btnMusica;
    private javax.swing.JButton btnNotas;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
    class ImagenFondo extends JPanel{
        private Image imagen;
        
        public void paint (Graphics g){
            imagen = new ImageIcon(getClass().getResource("fondoEscritorio.jpg")).getImage();
            g.drawImage(imagen, 0, 0, getWidth(), getHeight(), this);
            setOpaque(false);
            super.paint(g);
        }
    }

}
